### ISSUE TITLE
pyxplot fails to build on 10.11.1

### ISSUE THREAD

**Issue by dmzimmerman** [Homebrew/homebrew-x11#156]
When attempting to build/install pyxplot on 10.11.1, the procedure fails with the following:

```
==> make install
Last 15 lines from /Users/dmz/Library/Logs/Homebrew/pyxplot/02.make:
clang -Wall -g  obj/helpers/pyxplot_watch.o obj/coreUtils/dict.o obj/coreUtils/errorReport.o obj/coreUtils/list.o obj/coreUtils/memAlloc.o obj/coreUtils/stringList.o obj/stringTools/asciidouble.o obj/settings/settingTypes.o         -lfftw3 `xml2-config --libs` `gsl-config --libs` -ltermcap -lreadline -lz -lpng  -lm -o bin/pyxplot_watch
mkdir -p bin
clang -Wall -g  obj/helpers/pyxplot_fitshelper.o obj/stringTools/asciidouble.o         -lcfitsio -lfftw3 `xml2-config --libs` `gsl-config --libs` -ltermcap -lreadline -lz -lpng  -lm -o bin/pyxplot_fitshelper
mkdir -p bin/debug
clang -Wall -g  obj/helpers/pyxplot_watch.debug.o obj/coreUtils/dict.debug.o obj/coreUtils/errorReport.debug.o obj/coreUtils/list.debug.o obj/coreUtils/memAlloc.debug.o obj/coreUtils/stringList.debug.o obj/stringTools/asciidouble.debug.o obj/settings/settingTypes.debug.o   -lfftw3 `xml2-config --libs` `gsl-config --libs` -ltermcap -lreadline -lz -lpng  -lm -o bin/debug/pyxplot_watch
mkdir -p bin/install
Undefined symbols for architecture x86_64:
  "_history_list", referenced from:
      _ppl_directive_history in core.o
      _ppl_directive_save in core.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/pyxplot] Error 1
make: *** Waiting for unfinished jobs....
clang -Wall -g  obj/helpers/pyxplot_watch.install.o obj/coreUtils/dict.install.o obj/coreUtils/errorReport.install.o obj/coreUtils/list.install.o obj/coreUtils/memAlloc.install.o obj/coreUtils/stringList.install.o obj/stringTools/asciidouble.install.o obj/settings/settingTypes.install.o -lfftw3 `xml2-config --libs` `gsl-config --libs` -ltermcap -lreadline -lz -lpng  -lm -o bin/install/pyxplot_watch

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-x11/issues
```

**Comment by dunn** [comment]
Could you post `brew gist-logs pyxplot`, please? Thanks!

**Comment by dmzimmerman** [comment]
https://gist.github.com/b0f00b9f57ae3c89e160

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
