### ISSUE TITLE
terminator doesn't work on 10.9.5

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-x11#135]
On OS X 10.9.5 or 10.11, when I `brew install terminator` and then launch it with `terminator &`, it just gives me a blank, nonresponsive window with a single header line at the top. No running terminal session inside. The context menu will appear, but doing anything with it tends to make it lock up. (And resizing the window tends to make `terminator` segfault.

The output shows this, including a complaint about a missing config file.

```
$ terminator
2015-10-03 19:16:06.882 Python[99257:d07] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
ConfigBase::load: Unable to open /Users/janke/.config/terminator/config ([Errno 2] No such file or directory: '/Users/janke/.config/terminator/config')
Warning: python-keybinder is not installed. This means the hide_window shortcut will be unavailable
Unable to bind hide_window key, another instance/window has it.
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE'
ActivityWatch plugin unavailable: please install python-notify
PluginRegistry::load_plugins: Importing plugin activitywatch.py failed: 'module' object has no attribute 'AVAILABLE'
```

But creating that config file, either as blank or copying https://gist.github.com/jacaetevha/1719840, doesn't fix it: no error message about the missing file, but still no shell session inside the window. Same behavior for both Terminator 0.97 and 0.98.

Anyone know what I need to do to get Terminator working?

**Comment by abandin-stratio** [comment]
Same error, has anyone found a fix?
Regards

**Comment by laerus** [comment]
Unable to bind hide_window key, another instance/window has it.
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE

happened after i installed 'rxvt-unicode-256color' package

**Comment by apjanke** [comment]
No luck. I think it might be time to boneyard `terminator` if it just gives us a broken install.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
